// DO NOT EDIT! Auto-generated by github.com/mgutz/razor
package layout

import (
	"github.com/mgutz/gorazor/gorazor"
)

func Default(body, css, js gorazor.SafeBuffer, title string) gorazor.SafeBuffer {
	_buffer := gorazor.NewSafeBuffer()
	_buffer.WriteString("\n\n<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\" />\n    <title>")
	_buffer.WriteSafe(title)
	_buffer.WriteString("</title>\n    ")
	_buffer.WriteSafe(css)
	_buffer.WriteString("\n</head>\n<body>\n    <div class=\"container\">")
	_buffer.WriteSafe(body)
	_buffer.WriteString("</div>\n    ")
	_buffer.WriteSafe(js)
	_buffer.WriteString("\n  </body>\n</html>")

	return _buffer
}
